Add FIDO2 HMAC-secret support to ykluks-enroll and ykluks-open.

diff --git a/yubikey-luks-enroll b/yubikey-luks-enroll
--- a/yubikey-luks-enroll
+++ b/yubikey-luks-enroll
@@ -3,11 +3,93 @@ SLOT=7
 DISK="/dev/sda3"
 CLEAR_SLOT=0
 DBG=0
-YUBIKEY_LUKS_SLOT=2 #Set this in case the value is missing in /etc/ykluks.cfg
-
+YUBIKEY_LUKS_SLOT=2 #Set this in case the value is missing in ykluks.cfg
+CONFIG_FILE="/etc/ykluks.cfg"
+FIDO2_RELYING_PARTY="yubikey-luks.cornelinux.github.com"
+FIDO2_USERNAME="ykluks"
+FIDO2_CREDENTIAL_ID=
+FIDO2_CREDENTIAL_PUBKEY=
 
 set -e
-. /etc/ykluks.cfg
+. $CONFIG_FILE
+
+fido2_device() {
+    fido2-token -L | sed 's/:.*//'
+}
+
+sha256_base64() {
+    # Computes SHA256 over the given argument, converts the hash to a binary blob, and returns the
+    # base64 encoding of said blob.
+    /usr/bin/printf $(printf '%s' "$1" | sha256sum | awk '{print $1}' | sed -e 's/\([0-9a-f]\{2\}\)/\\x\1/g') | base64 -w0
+}
+
+fido2_salt_from_blkid() {
+    sha256_base64 "$(blkid -o value "$1" | head -1)"
+}
+
+fido2_update_config() {
+    if ! grep -qE "[^\\t ]*FIDO2_$1=" $CONFIG_FILE ; then
+        printf '\nFIDO2_%s="%s"\n' "$1" "$2" >> $CONFIG_FILE
+    else
+        local sed_script=$(printf 's;[^\\t ]*FIDO2_%s=.*$;FIDO2_%s="%s";' $1 $1 $2)
+        sed -i -e "$sed_script" $CONFIG_FILE
+    fi
+}
+
+fido2_temp_keyfile() {
+    local keyfile=$(mktemp)
+    echo "$FIDO2_CREDENTIAL_PUBKEY" | base64 -d > $keyfile
+    echo $keyfile
+}
+
+fido2_create_credential() {
+    local challenge=$(dd if=/dev/urandom bs=1 count=32 2> /dev/null | base64)
+    local user_id=$(printf '%s' "$FIDO2_USERNAME" | base64)
+    local params="$challenge\n$FIDO2_RELYING_PARTY\n$FIDO2_USERNAME\n$user_id"
+    if [ "$DBG" = "1" ]; then echo "Credential parameters: \n$params\n"; fi
+
+    local cred=$(echo "$params" | fido2-cred -M $(fido2_device) | fido2-cred -V)
+    if [ "$DBG" = "1" ]; then echo "Credential response: \n$cred\n"; fi
+    if [ -z "$cred" ] ; then
+        return 1
+    fi
+
+    # We base64 encode the already PEM encoded pubkey to fit it on one line in the config.
+    FIDO2_CREDENTIAL_PUBKEY="$(printf '%s\n' "$cred" | tail -n+2 | base64 -w0)"
+    FIDO2_CREDENTIAL_ID="$(printf '%s\n' "$cred" | head -1)"
+}
+
+fido2_enroll() {
+    if [ "$FIDO2_CREDENTIAL_ID" = "" ] ; then
+        echo "No credential configured. Creating a new one."
+        if ! fido2_create_credential ; then
+            echo "Unable to create FIDO2 credential."
+            exit 1
+        fi
+
+        if [ "$DBG" = "1" ]; then echo "Saving FIDO2 credential ID and public key to config."; fi
+        fido2_update_config CREDENTIAL_ID "$FIDO2_CREDENTIAL_ID"
+        fido2_update_config CREDENTIAL_PUBKEY "$FIDO2_CREDENTIAL_PUBKEY"
+    fi
+
+    local salt=$(fido2_salt_from_blkid)
+    local challenge=$(dd if=/dev/urandom bs=1 count=32 2> /dev/null | base64)
+    local params="$challenge\n$FIDO2_RELYING_PARTY\n$FIDO2_CREDENTIAL_ID\n$salt"
+    if [ "$DBG" = "1" ]; then echo "Assertion parameters: \n$params\n"; fi
+
+    local assertion=$(echo "$params" | fido2-assert -G -h -v $(fido2_device))
+    if [ "$DBG" = "1" ]; then echo "Assertion response: \n$assertion\n"; fi
+    if [ -z "$assertion" ] ; then
+        echo "Unable to generate shared secret."
+        exit 1
+    fi
+
+    local keyfile=$(fido2_temp_keyfile)
+
+    echo "$assertion" | head -n4 | fido2-assert -V -h $keyfile || (rm -f $keyfile ; exit 1)
+    rm -f $keyfile
+    R=$(printf '%s\n' "$assertion" | tail -1)
+}
 
 if [ "$(id -u)" -ne 0 ]; then
     echo "You must be root." 1>&2
@@ -28,7 +110,7 @@ while getopts ":s:d:y:hcv" opt; do
         if [ ! "$YUBIKEY_LUKS_SLOT" = "$OPTARG" ]; then
            echo "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
            echo "WARNING: You are enrolling slot $OPTARG of your yubikey."
-           echo "During boot, slot $YUBIKEY_LUKS_SLOT is configured to be used (/etc/ykluks.cfg)."
+           echo "During boot, slot $YUBIKEY_LUKS_SLOT is configured to be used ($CONFIG_FILE)."
            echo "You will therefore not be able to boot using this setup!"
            echo "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
         fi
@@ -73,28 +155,35 @@ while true ; do
     read -r _ <&1
 done
 
-P1=$(/lib/cryptsetup/askpass "Please enter the yubikey challenge password. This is the password that will only work while your yubikey is installed in your computer:")
-if [ "$DBG" = "1" ]; then echo "Password: $P1"; fi
+if [ "$YUBIKEY_LUKS_SLOT" = "fido2" ] ; then
+    # Hash and concatenate don't make sense in FIDO2 mode.
+    HASH=0
+    CONCATENATE=0
+    fido2_enroll
+else
+    P1=$(/lib/cryptsetup/askpass "Please enter the yubikey challenge password. This is the password that will only work while your yubikey is installed in your computer:")
+    if [ "$DBG" = "1" ]; then echo "Password: $P1"; fi
 
-P2=$(/lib/cryptsetup/askpass "Please enter the yubikey challenge password again:")
-if [ "$DBG" = "1" ]; then echo "Password: $P2"; fi
+    P2=$(/lib/cryptsetup/askpass "Please enter the yubikey challenge password again:")
+    if [ "$DBG" = "1" ]; then echo "Password: $P2"; fi
 
-if [ "$P1" != "$P2" ]; then
-    echo "Passwords do not match"
-    exit 1
-fi
+    if [ "$P1" != "$P2" ]; then
+        echo "Passwords do not match"
+        exit 1
+    fi
 
-if [ "$HASH" = "1" ]; then
-    P1=$(printf %s "$P1" | sha256sum | awk '{print $1}')
-    if [ "$DBG" = "1" ]; then echo "Password hash: $P1"; fi
-fi
+    if [ "$HASH" = "1" ]; then
+        P1=$(printf %s "$P1" | sha256sum | awk '{print $1}')
+        if [ "$DBG" = "1" ]; then echo "Password hash: $P1"; fi
+    fi
 
-R="$(printf %s "$P1" | ykchalresp -"$YUBIKEY_LUKS_SLOT" -i- 2>/dev/null || true)"
-if [ "$DBG" = "1" ]; then echo "Yubikey response: $R"; fi
+    R="$(printf %s "$P1" | ykchalresp -"$YUBIKEY_LUKS_SLOT" -i- 2>/dev/null || true)"
+    if [ "$DBG" = "1" ]; then echo "Yubikey response: $R"; fi
 
-if [ -z "$R" ]; then
-    echo "Yubikey not available or timed out waiting for button press"
-    exit 1
+    if [ -z "$R" ]; then
+        echo "Yubikey not available or timed out waiting for button press"
+        exit 1
+    fi
 fi
 
 OLD=$(/lib/cryptsetup/askpass "Please provide an existing passphrase. This is NOT the passphrase you just entered, this is the passphrase that you currently use to unlock your LUKS encrypted drive:")
diff --git a/yubikey-luks-open b/yubikey-luks-open
--- a/yubikey-luks-open
+++ b/yubikey-luks-open
@@ -2,10 +2,35 @@
 DISK="/dev/sda3"
 NAME="yubikey-luks"
 DBG=0
-YUBIKEY_LUKS_SLOT=2 #Set this in case the value is missing in /etc/ykluks.cfg
+YUBIKEY_LUKS_SLOT=2 #Set this in case the value is missing in ykluks.cfg
+CONFIG_FILE="/etc/ykluks.cfg"
+FIDO2_RELYING_PARTY="yubikey-luks.cornelinux.github.com"
+FIDO2_USERNAME="ykluks"
+FIDO2_CREDENTIAL_ID=
+FIDO2_CREDENTIAL_PUBKEY=
 
 set -e
-. /etc/ykluks.cfg
+. $CONFIG_FILE
+
+sha256_base64() {
+    # Computes SHA256 over the given argument, converts the hash to a binary blob, and returns the
+    # base64 encoding of said blob.
+    /usr/bin/printf $(printf '%s' "$1" | sha256sum | awk '{print $1}' | sed -e 's/\([0-9a-f]\{2\}\)/\\x\1/g') | base64 -w0
+}
+
+fido2_salt_from_blkid() {
+    sha256_base64 "$(blkid -o value "$1" | head -1)"
+}
+
+fido2_device() {
+    fido2-token -L | sed 's/:.*//'
+}
+
+fido2_temp_keyfile() {
+    local keyfile=$(mktemp)
+    echo "$FIDO2_CREDENTIAL_PUBKEY" | base64 -d > $keyfile
+    echo $keyfile
+}
 
 while getopts ":d:n:hv" opt; do
     case $opt in
@@ -43,27 +68,46 @@ while true ; do
     read -r _ <&1
 done
 
-P1=$(/lib/cryptsetup/askpass "Enter password created with yubikey-luks-enroll:")
-if [ "$DBG" = "1" ]; then echo "Password: $P1"; fi
-
-if [ "$HASH" = "1" ]; then
-    P1=$(printf %s "$P1" | sha256sum | awk '{print $1}')
-    if [ "$DBG" = "1" ]; then echo "Password hash: $P1"; fi
-fi
-
-R="$(printf %s "$P1" | ykchalresp -"$YUBIKEY_LUKS_SLOT" -i- 2>/dev/null || true)"
-if [ "$DBG" = "1" ]; then echo "Yubikey response: $R"; fi
-
-if [ -z "$R" ]; then
-    echo "Yubikey not available or timed out waiting for button press"
-    exit 1
-fi
-
 _passphrase=''
-if [ "$CONCATENATE" = "1" ]; then
-    _passphrase=$(printf '%s' "$P1$R")
+if [ "$YUBIKEY_LUKS_SLOT" = "fido2" ] ; then
+    salt=$(fido2_salt_from_blkid)
+    challenge=$(dd if=/dev/urandom bs=1 count=32 2> /dev/null | base64)
+    params="$challenge\n$FIDO2_RELYING_PARTY\n$FIDO2_CREDENTIAL_ID\n$salt"
+    if [ "$DBG" = "1" ]; then echo "Assertion parameters: \n$params\n"; fi
+
+    assertion=$(echo "$params" | fido2-assert -G -h -v $(fido2_device))
+    if [ "$DBG" = "1" ]; then echo "Assertion response: \n$assertion\n"; fi
+    if [ -z "$assertion" ] ; then
+        echo "Unable to generate shared secret."
+        exit 1
+    fi
+
+    keyfile=$(fido2_temp_keyfile)
+    echo "$assertion" | head -n4 | fido2-assert -V -h "$keyfile" || (rm -f $keyfile ; exit 1)
+    rm -f $keyfile
+    _passphrase=$(printf '%s\n' "$assertion" | tail -1)
 else
-    _passphrase=$(printf '%s' "$R")
+    P1=$(/lib/cryptsetup/askpass "Enter password created with yubikey-luks-enroll:")
+    if [ "$DBG" = "1" ]; then echo "Password: $P1"; fi
+
+    if [ "$HASH" = "1" ]; then
+        P1=$(printf %s "$P1" | sha256sum | awk '{print $1}')
+        if [ "$DBG" = "1" ]; then echo "Password hash: $P1"; fi
+    fi
+
+    R="$(printf %s "$P1" | ykchalresp -"$YUBIKEY_LUKS_SLOT" -i- 2>/dev/null || true)"
+    if [ "$DBG" = "1" ]; then echo "Yubikey response: $R"; fi
+
+    if [ -z "$R" ]; then
+        echo "Yubikey not available or timed out waiting for button press"
+        exit 1
+    fi
+
+    if [ "$CONCATENATE" = "1" ]; then
+        _passphrase=$(printf '%s' "$P1$R")
+    else
+        _passphrase=$(printf '%s' "$R")
+    fi
 fi
 if [ "$DBG" = "1" ]; then echo "LUKS key: ${_passphrase}"; fi
 
