replace all tab stops with 4 whitespaces

diff --git a/yubikey-luks-open b/yubikey-luks-open
--- a/yubikey-luks-open
+++ b/yubikey-luks-open
@@ -9,29 +9,29 @@ set -e
 
 while getopts ":d:n:hv" opt; do
     case $opt in
-	d)
-	    DISK=$OPTARG
-	    echo "setting disk to $OPTARG."
-	    ;;
-	n)
-	    NAME=$OPTARG
-	    echo "setting name to $OPTARG."
-	    ;;
-	v)
-	    DBG=1
-	    echo "debugging enabled"
-	    ;;
-	h)
-	    echo
-	    echo " -d <partition>: select existing partition"
-	    echo " -n <name>     : set the new container name"
-	    echo " -v            : show input/output in cleartext"
-	    echo
-	    exit 1
-	    ;;
-	\?)
-	    echo "Invalid option: -$OPTARG" >&2
-	    ;;
+    d)
+        DISK=$OPTARG
+        echo "setting disk to $OPTARG."
+        ;;
+    n)
+        NAME=$OPTARG
+        echo "setting name to $OPTARG."
+        ;;
+    v)
+        DBG=1
+        echo "debugging enabled"
+        ;;
+    h)
+        echo
+        echo " -d <partition>: select existing partition"
+        echo " -n <name>     : set the new container name"
+        echo " -v            : show input/output in cleartext"
+        echo
+        exit 1
+        ;;
+    \?)
+        echo "Invalid option: -$OPTARG" >&2
+        ;;
     esac
 done
 
@@ -83,14 +83,14 @@ else
     expect_script=''
     OLDIFS="$IFS"
     while IFS="${_n}" read -r line; do
-	expect_script="$expect_script$line${_n}"
+    expect_script="$expect_script$line${_n}"
     done <<EXPECTSCRIPT
-		set timeout -1;
-		spawn udisksctl unlock -b "$DISK";
-		match_max 100000;
-		expect -exact "Passphrase: ";
-		send -- "${_passphrase}\\r";
-		expect eof
+        set timeout -1;
+        spawn udisksctl unlock -b "$DISK";
+        match_max 100000;
+        expect -exact "Passphrase: ";
+        send -- "${_passphrase}\\r";
+        expect eof
 EXPECTSCRIPT
     # get rid of all tabs and convert newlines to spaces in the expect script,
     # otherwise it will break when it is piped to expect
